# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - run: yarn build
      - run: |
          git config --global user.email "lif3ng@deploy"
          git config --global user.name "lif3ng"
      - run: |
          cd docs/.vuepress/dist
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://lif3ng:${{ secrets.LIF3NG_PUSH_TOKEN }}@github.com/web-playground/web-playground.github.io.git master:gh-pages
